// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38m8azYstPKC739zgQuqBK1JsU2z_Q-M',
    appId: '1:669670948896:web:d5e88b14f5405c59f17c45',
    messagingSenderId: '669670948896',
    projectId: 'hotel-booking-36e38',
    authDomain: 'hotel-booking-36e38.firebaseapp.com',
    storageBucket: 'hotel-booking-36e38.firebasestorage.app',
    measurementId: 'G-R25GB7BQWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnlVCSWv-0nIi0xzQlw3WGP36UNULW3fE',
    appId: '1:669670948896:android:9d71d09b551af614f17c45',
    messagingSenderId: '669670948896',
    projectId: 'hotel-booking-36e38',
    storageBucket: 'hotel-booking-36e38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Rc6H2zGnM9BIQ150YTWyweFQKuNi27E',
    appId: '1:669670948896:ios:49c855e40835ce16f17c45',
    messagingSenderId: '669670948896',
    projectId: 'hotel-booking-36e38',
    storageBucket: 'hotel-booking-36e38.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Rc6H2zGnM9BIQ150YTWyweFQKuNi27E',
    appId: '1:669670948896:ios:49c855e40835ce16f17c45',
    messagingSenderId: '669670948896',
    projectId: 'hotel-booking-36e38',
    storageBucket: 'hotel-booking-36e38.firebasestorage.app',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD38m8azYstPKC739zgQuqBK1JsU2z_Q-M',
    appId: '1:669670948896:web:1069f21b51cf9b6af17c45',
    messagingSenderId: '669670948896',
    projectId: 'hotel-booking-36e38',
    authDomain: 'hotel-booking-36e38.firebaseapp.com',
    storageBucket: 'hotel-booking-36e38.firebasestorage.app',
    measurementId: 'G-4J6QSPMNG9',
  );
}
